title: CAIRO Hackathon
description: A quarterly Hackathon co-organiazed by CAIRO THWS and Würzburg Deep Learning Meetup
show_downloads: false
google_analytics:
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
